- name: node js
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd


- name: mongodb setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-setup